apiVersion: app/v1
kind: ReplicaSet
metadata:
  name: rc-nginx
  labels:
    env: demo
replicas: 4
spec:
  template:
    metadata:
      labels:
        env: demo
        name: nginx-pod
    spec:
      containers:
        - name: nginx
          image: nginx:latest